name: Build and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      #Extract version from pyproject.toml
      - name: Extract version from pyproject.toml
        run: |
          version=$(python -c "
          import tomllib
          with open('pyproject.toml','rb') as f:
            v = tomllib.load(f)['project']['version']
            print(v)
          ")
          version=${version%.dev*}
          echo "VERSION=$version" >> $GITHUB_ENV
      
      - name: Create GitHub Tag
        run: |
          git fetch --tags

          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION }} already exists. Skipping..."
            exit 0
          fi
        
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"


      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      #Build Docker image
      - name: Build and Push Docker Image
        run: |
          IMG="ghcr.io/${{github.repository}}:v${{ env.VERSION }}"
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMG --push .
      
  bump-version:
    runs-on: ubuntu-latest
    needs: build-and-release 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
    
          
      #next snapshot version
      - name: calculate next version
        run: |
          version=$(python -c "
          import tomllib
          with open('pyproject.toml','rb') as f:
            v = tomllib.load(f)['project']['version']
            print(v)
          ")       
          curr_version=${version%.dev*}
          major=$(echo "$curr_version" | cut -d . -f 1)
          minor=$(echo "$curr_version" | cut -d . -f 2)
          patch=$(echo "$curr_version" | cut -d . -f 3)
          next_patch=$((patch+1)) 
          new_version="${major}.${minor}.${next_patch}.dev0"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Install tomli_w
        run: pip install tomli_w   

      #Commit new version
      - name: commit new version
        run:  |
          python - <<EOF
          import tomllib, tomli_w
          with open('pyproject.toml','rb') as f:
            data = tomllib.load(f)
            data['project']['version'] = '${{ env.NEW_VERSION }}'
          with open("pyproject.toml", "wb") as f:
            tomli_w.dump(data, f)
          EOF
          git config user.name "GitHub Actions" 
          git config user.email "actions@github.com" 
          git add pyproject.toml
          git commit -am "chore: bump version to ${{ env.NEW_VERSION }} [skip ci]" 
          git push origin master