name: Build and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install xmllstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet
          
      #Extract version from pom.xml
      - name: Extract version from pom.xml
        run: |
          version=$(xmlstarlet sel -t -v "/*[local-name()='project']/*[local-name()='version']" pom.xml)
          version=${version%-SNAPSHOT}
          echo "VERSION=$version" >> $GITHUB_ENV
      
      - name: Create GitHub Tag
        run: |
          git fetch --tags

          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION }} already exists. Skipping..."
            exit 0
          fi
        
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"


      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
    
      #Build Docker image
      - name: Build and Push Docker Image
        run: |
          IMG="ghcr.io/${{github.repository}}:v${{ env.VERSION }}"
          docker build -t $IMG .
          docker push $IMG
      
  bump-version:
    runs-on: ubuntu-latest
    needs: build-and-release 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Install xmllstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet
          
      #next snapshot version
      - name: calculate next version
        run: |
          version=$(xmlstarlet sel -t -v "/*[local-name()='project']/*[local-name()='version']" pom.xml)
          curr_version=${version%-SNAPSHOT}
          major=$(echo "$curr_version" | cut -d . -f 1)
          minor=$(echo "$curr_version" | cut -d . -f 2)
          patch=$(echo "$curr_version" | cut -d . -f 3)
          next_patch=$((patch+1)) 
          new_version="${major}.${minor}.${next_patch}-SNAPSHOT"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
              
      #Commit new version
      - name: commit new version
        run:  |
          mvn versions:set -DnewVersion=${{ env.NEW_VERSION }} -DgenerateBackupPoms=false
          git config user.name "GitHub Actions" 
          git config user.email "actions@github.com" 
          git commit -am "chore: bump version to ${{ env.NEW_VERSION }} [skip ci]" 
          git push origin main